### ISSUE TITLE
Fatal error: Class 'Illuminate\Events\Dispatcher' not found

### ISSUE THREAD

**Issue by adskiremote** [rayokota/generator-angular-slim#7]
Hi I'm getting the error

Fatal error: Class 'Illuminate\Events\Dispatcher' not found

When I run the service using: php -S 127.0.0.1:8080 -t public

Do you know what this is referring to?  I have also created an entity and this has the same error.

**Comment by adskiremote** [comment]
thank you

**Comment by da-production** [comment]
> Hi I'm getting the error
> 
> Fatal error: Class 'Illuminate\Events\Dispatcher' not found
> 
> When I run the service using: php -S 127.0.0.1:8080 -t public
> 
> Do you know what this is referring to? I have also created an entity and this has the same error.

if u use it outside framework in specif project u need to require in your composer.json file this :
"illuminate/events": "5.2.*"
composer require illuminate/events
